# Generated by Django 5.1.5 on 2025-07-26 04:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_account_file', models.FileField(help_text='Google service account credentials JSON file', upload_to='credentials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('drive_folder_url', models.URLField(blank=True, help_text='Google Drive folder URL containing the budget sheets')),
                ('folder_id', models.CharField(blank=True, help_text='Extracted Google Drive folder ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Google Drive Credentials',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('direct_upload', 'Direct Upload')], max_length=20)),
                ('name', models.CharField(help_text='Friendly name for this source', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sources', to=settings.AUTH_USER_MODEL)),
                ('google_credentials', models.ForeignKey(blank=True, help_text='Required for Google Drive sources', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.googledrivecredentials')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
