# Generated by Django 5.1.5 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("google_drive", "Google Drive"),
                    ("direct_upload", "Direct Upload"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
