# Generated by Django 5.1.5 on 2025-07-26 04:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_id', models.CharField(blank=True, help_text='Google Sheet ID for tracking and sync purposes', max_length=255)),
                ('google_sheet_name', models.CharField(blank=True, help_text='Original Google Sheet name', max_length=255)),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year (e.g., 2025)')),
                ('csv_file', models.FileField(help_text='Processed CSV file containing expenses and income', upload_to='documents/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Total expenses for this month', max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income for this month', max_digits=15)),
                ('expenses_count', models.PositiveIntegerField(default=0, help_text='Number of expense entries')),
                ('income_count', models.PositiveIntegerField(default=0, help_text='Number of income entries')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.documentsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
