# Generated by Django 5.1.5 on 2026-10-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="csv_file",
            field=models.FileField(
                blank=True,
                help_text="Processed CSV file containing expenses and income",
                upload_to="documents/csv/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["csv"])],
            ),
        ),
    ]
