# Generated by Django 6.0.5 on 2026-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_user_alter_transaction_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("google_sheets", "Google Sheets"),
                    ("direct_upload", "Direct Upload"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
