# Generated by Django 6.0.5 on 2026-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_backfill_transaction_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("google_sheets", "Google Sheets"),
                    ("direct_upload", "Direct Upload"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
