# Generated by Django 6.0.5 on 2026-10-04 00:00

from typing import Any

from django.db import migrations, models


def clear_transaction_origins(apps: Any, schema_editor: Any) -> None:
    """Clear values after the origin field becomes nullable during rollback."""

    transaction_model = apps.get_model("transactions", "Transaction")
    transaction_model.objects.update(origin=None)


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_backfill_transaction_origin"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, clear_transaction_origins),
        migrations.AlterField(
            model_name="transaction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("google_sheets", "Google Sheets"),
                    ("direct_upload", "Direct Upload"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
