# Generated by Django 5.1.5 on 2026-10-01 15:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the budgeted month')),
                ('note', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, help_text='Hex colour such as #2f6f4f', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('type', 'sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.budgetperiod')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.category')),
            ],
            options={
                'ordering': ('category__sort_order', 'category__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('e_wallet', 'E-wallet'), ('credit', 'Credit'), ('investment', 'Investment'), ('other', 'Other')], default='cash', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_balance_date', models.DateField()),
                ('include_in_budget', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, help_text='Hex colour such as #2f6f4f', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('occurred_on', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.category')),
                ('transfer_account', models.ForeignKey(blank=True, help_text='Destination account, transfers only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='ledger.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_on', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='ledger_budget_period_month_uniq'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'archived_at'], name='ledger_category_listing_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'type', 'name'), name='ledger_category_active_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.UniqueConstraint(fields=('period', 'category'), name='ledger_allocation_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='ledger_allocation_amount_not_negative'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'archived_at', 'sort_order'], name='ledger_account_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['user', '-occurred_on', '-id'], name='ledger_txn_user_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_txn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('transfer_account__isnull', True), ('type__in', ('income', 'expense'))), models.Q(('category__isnull', True), ('transfer_account__isnull', False), ('type', 'transfer')), _connector='OR'), name='ledger_txn_shape_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_account__isnull', True), models.Q(('transfer_account', models.F('account')), _negated=True), _connector='OR'), name='ledger_txn_transfer_differs'),
        ),
    ]
