# Generated by Django 5.1.5 on 2026-09-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreedomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freedom_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_archived', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='FreedomScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved')], default='draft', max_length=10)),
                ('calculation_date', models.DateField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField()),
                ('source_mode', models.CharField(choices=[('manual', 'Manual'), ('tracked_actuals', 'Tracked actuals')], default='manual', max_length=20)),
                ('source_period_start', models.DateField(blank=True, null=True)),
                ('source_period_end', models.DateField(blank=True, null=True)),
                ('source_month_count', models.PositiveSmallIntegerField(default=0)),
                ('source_excluded_income_categories', models.JSONField(blank=True, default=list)),
                ('source_excluded_expense_categories', models.JSONField(blank=True, default=list)),
                ('current_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_monthly_investment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_investable_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('emergency_savings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('desired_monthly_lifestyle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('post_freedom_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('withdrawal_rate', models.DecimalField(decimal_places=3, default=4, max_digits=6)),
                ('annual_return_rate', models.DecimalField(decimal_places=3, default=7, max_digits=6)),
                ('annual_inflation_rate', models.DecimalField(decimal_places=3, default=3, max_digits=6)),
                ('annual_income_growth_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('annual_contribution_growth_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('safety_buffer_rate', models.DecimalField(decimal_places=3, default=10, max_digits=6)),
                ('include_emergency_reserve_in_target', models.BooleanField(default=False)),
                ('base_freedom_number', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('required_monthly_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('projected_achievement_date', models.DateField(blank=True, null=True)),
                ('funding_gap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('progress_percent', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('result_status', models.CharField(choices=[('on_track', 'On track'), ('behind', 'Behind'), ('unreachable', 'Unreachable'), ('complete', 'Complete')], default='behind', max_length=20)),
                ('projection_data', models.JSONField(blank=True, default=dict)),
                ('calculation_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_scenarios', to='financial_planning.freedomscenario')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='financial_planning.freedomplan')),
            ],
            options={
                'ordering': ('-version', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('car', 'Car'), ('home', 'Home'), ('wedding', 'Wedding'), ('education', 'Education'), ('business', 'Business'), ('medical', 'Medical'), ('family', 'Family support'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('event_date', models.DateField()),
                ('one_time_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_basis', models.CharField(choices=[('today', "Today's money"), ('event_date', 'Event-date money')], default='today', max_length=20)),
                ('recurring_monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(choices=[('investment_portfolio', 'Investment portfolio'), ('separate_savings', 'Separate savings')], default='investment_portfolio', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='financial_planning.freedomscenario')),
            ],
            options={
                'ordering': ('sort_order', 'event_date', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='freedomplan',
            index=models.Index(fields=['user', 'is_archived', '-updated_at'], name='freedom_plan_library_idx'),
        ),
        migrations.AddIndex(
            model_name='freedomscenario',
            index=models.Index(fields=['plan', 'status', '-version'], name='freedom_scenario_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='freedomscenario',
            index=models.Index(fields=['plan', 'status', '-created_at'], name='freedom_scenario_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='freedom_scenario_plan_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('plan',), name='freedom_scenario_one_draft_uniq'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(('target_date__gt', models.F('calculation_date'))), name='freedom_scenario_target_after_calc'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('version', 0)), models.Q(('status', 'saved'), ('version__gte', 1)), _connector='OR'), name='freedom_scenario_version_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(('current_monthly_income__gte', 0), ('current_monthly_expenses__gte', 0), ('current_monthly_investment__gte', 0), ('current_investable_assets__gte', 0), ('emergency_savings__gte', 0), ('desired_monthly_lifestyle__gte', 0), ('post_freedom_monthly_income__gte', 0)), name='freedom_scenario_money_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(('withdrawal_rate__gt', 0), ('withdrawal_rate__lte', 10)), name='freedom_scenario_withdrawal_range'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(('safety_buffer_rate__gte', 0), ('safety_buffer_rate__lte', 100)), name='freedom_scenario_buffer_range'),
        ),
        migrations.AddConstraint(
            model_name='freedomscenario',
            constraint=models.CheckConstraint(condition=models.Q(('annual_return_rate__gte', -99), ('annual_return_rate__lte', 100), ('annual_inflation_rate__gte', -99), ('annual_inflation_rate__lte', 100), ('annual_income_growth_rate__gte', -99), ('annual_income_growth_rate__lte', 100), ('annual_contribution_growth_rate__gte', -99), ('annual_contribution_growth_rate__lte', 100)), name='freedom_scenario_annual_rate_range'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['scenario', 'sort_order'], name='financial_event_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.CheckConstraint(condition=models.Q(('one_time_amount__gte', 0), ('recurring_monthly_amount__gte', 0)), name='financial_event_money_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.CheckConstraint(condition=models.Q(('one_time_amount__gt', 0), ('recurring_monthly_amount__gt', 0), _connector='OR'), name='financial_event_has_cost'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.CheckConstraint(condition=models.Q(('recurring_end_date__isnull', True), ('recurring_end_date__gte', models.F('event_date')), _connector='OR'), name='financial_event_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.CheckConstraint(condition=models.Q(('recurring_monthly_amount', 0), ('recurring_end_date__isnull', False), _connector='OR'), name='financial_event_recurring_has_end'),
        ),
    ]
